In [1]:
import numpy as np
import os

print("Numpy Version is ", np.__version__)


Numpy Version is  1.15.4


In [2]:
# Saving NumPy array as a csv file
array_rain_fall = np.loadtxt(fname="rain-fall.csv", delimiter=",")
np.savetxt(fname="saved-rain-fall-row-col-names.csv", delimiter=",", X=array_rain_fall)

# Check generated csv file after loading it

array_rain_fall_csv_saved = np.loadtxt(
    fname="saved-rain-fall-row-col-names.csv", delimiter=","
)

print("NumPy array: \n", array_rain_fall_csv_saved)
print("Shape: ", array_rain_fall_csv_saved.shape)
print("Data Type: ", array_rain_fall_csv_saved.dtype.name)

# We can change our delimeter and save file in tsv or other text format


NumPy array: 
 [[12.  12.  14.  16.  19.  12.  11.  14.  17.  19.  11.  11.5]
 [13.  11.  13.5 16.7 15.  11.  12.  11.  19.  18.  13.  12.5]]
Shape:  (2, 12)
Data Type:  float64


In [3]:

# Saving array as binary file and reading it

array_rain_fall.tofile("saved-rain-fall-binary")

array_rain_fall_binary = np.fromfile("saved-rain-fall-binary")

print("NumPy array: \n", array_rain_fall_binary)
print("Shape: ", array_rain_fall_binary.shape)
print("Data Type: ", array_rain_fall_binary.dtype.name)


NumPy array: 
 [12.  12.  14.  16.  19.  12.  11.  14.  17.  19.  11.  11.5 13.  11.
 13.5 16.7 15.  11.  12.  11.  19.  18.  13.  12.5]
Shape:  (24,)
Data Type:  float64


In [4]:

# Saving array as .npy and reading it

np.save("saved-rain-fall-binary.npy", array_rain_fall)

array_rain_fall_npy = np.load("saved-rain-fall-binary.npy")

print("NumPy array: \n", array_rain_fall_npy)
print("Shape: ", array_rain_fall_npy.shape)
print("Data Type: ", array_rain_fall_npy.dtype.name)


NumPy array: 
 [[12.  12.  14.  16.  19.  12.  11.  14.  17.  19.  11.  11.5]
 [13.  11.  13.5 16.7 15.  11.  12.  11.  19.  18.  13.  12.5]]
Shape:  (2, 12)
Data Type:  float64


In [5]:

# Saving multiple arrays in compressed npz format. Loading and reading the array.

np.savez("saved-rain-fall-binary.npz", array_rain_fall, np.array([1, 2, 3, 4, 5]))

array_rain_fall_npz = np.load("saved-rain-fall-binary.npz")

print("NumPy array 1: \n", array_rain_fall_npz["arr_0"])
print("Shape of Array 1: ", array_rain_fall_npz["arr_0"].shape)
print("Data Type of Array 1: ", array_rain_fall_npz["arr_0"].dtype.name)

print("NumPy array 2: \n", array_rain_fall_npz["arr_1"])
print("Shape of Array 2: ", array_rain_fall_npz["arr_1"].shape)
print("Data Type of Array 2: ", array_rain_fall_npz["arr_1"].dtype.name)


NumPy array 1: 
 [[12.  12.  14.  16.  19.  12.  11.  14.  17.  19.  11.  11.5]
 [13.  11.  13.5 16.7 15.  11.  12.  11.  19.  18.  13.  12.5]]
Shape of Array 1:  (2, 12)
Data Type of Array 1:  float64
NumPy array 2: 
 [1 2 3 4 5]
Shape of Array 2:  (5,)
Data Type of Array 2:  int64
